# Generated by Django 5.2.14 on 2026-05-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_data_loggers'),
        ('core', '0002_etssite_etssitebilling_etssitebillingconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ets_sites',
            field=models.ManyToManyField(blank=True, to='core.etssite'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('engineer', 'Engineer'), ('admin', 'Admin'), ('operator', 'Operator'), ('user', 'User')], max_length=20),
        ),
    ]
