# Generated by Django 6.0 on 2026-05-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataLogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('region', models.CharField(blank=True, choices=[('dubai', 'Dubai'), ('northern_region', 'Northern Region'), ('abu_dhabi', 'Abu Dhabi')], max_length=30, null=True)),
                ('country', models.CharField(choices=[('UAE', 'United Arab Emirates')], default='UAE', max_length=10)),
                ('connected', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('alarm_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10)),
                ('base_topic', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
    ]
