# Generated by Django 5.2.14 on 2026-05-07 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_data_loggers'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETSSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ets_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('cts_name', models.CharField(blank=True, max_length=200, null=True)),
                ('plot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('region', models.CharField(blank=True, choices=[('dubai', 'Dubai'), ('northern_region', 'Northern Region'), ('abu_dhabi', 'Abu Dhabi')], max_length=30, null=True)),
                ('country', models.CharField(choices=[('UAE', 'United Arab Emirates')], default='UAE', max_length=10)),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('declared_load', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contracted_delta_t', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('connected', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('alarm_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ETS Site',
                'db_table': 'core_ets_site',
            },
        ),
        migrations.CreateModel(
            name='ETSSiteBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('average_delta_t', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delta_t_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('consumption_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ets_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='core.etssite')),
            ],
            options={
                'verbose_name': 'ETS Site Billing',
                'db_table': 'core_ets_site_billing',
                'ordering': ['-from_date'],
            },
        ),
        migrations.CreateModel(
            name='ETSSiteBillingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta_t_reference', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('delta_t_tolerance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('delta_t_fee_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('consumption_fee_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ets_site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_config', to='core.etssite')),
            ],
            options={
                'verbose_name': 'ETS Site Billing Config',
                'db_table': 'core_ets_site_billing_config',
            },
        ),
        migrations.CreateModel(
            name='ETSSiteReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('supply_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('return_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('delta_t', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('flow_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ets_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.etssite')),
            ],
            options={
                'verbose_name': 'ETS Site Reading',
                'db_table': 'core_ets_site_reading',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='DataLogger',
        ),
        migrations.AddIndex(
            model_name='etssitebilling',
            index=models.Index(fields=['ets_site', 'from_date', 'to_date'], name='core_ets_si_ets_sit_f8736d_idx'),
        ),
        migrations.AddIndex(
            model_name='etssitereading',
            index=models.Index(fields=['ets_site', 'timestamp'], name='core_ets_si_ets_sit_924e6a_idx'),
        ),
    ]
