# Generated by Django 5.2.14 on 2026-05-07 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_etssite_etssitebilling_etssitebillingconfig_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ETSSiteReading',
        ),
    ]
