# Generated by Django 6.0 on 2026-05-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_etssite_contract_document_etssitebillingconfig_billing_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='etssite',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etssitebilling',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
