# Generated by Django 6.0 on 2026-05-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_etssitebillingconfig_delta_t_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etssite',
            old_name='cts_name',
            new_name='ets_name',
        ),
        migrations.AddField(
            model_name='etssite',
            name='declared_load_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='etssitebilling',
            name='declared_load_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='etssitebilling',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
