# Generated by Django 6.0 on 2026-05-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_cts_name_etssite_ets_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etssite',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
