# Generated by Django 6.0 on 2026-05-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_etssite_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etssitebillingconfig',
            name='delta_t_tolerance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
    ]
