# Generated by Django 6.0 on 2026-05-07 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OPCConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('endpoint_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OPCNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('opc_name', models.CharField(max_length=255)),
                ('opc_address', models.TextField()),
                ('data_type', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OPCNodeLive',
            fields=[
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='opc.opcnode')),
                ('value', models.FloatField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('source_ts', models.DateTimeField(null=True)),
                ('server_ts', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OPCObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('opc_name', models.CharField(max_length=255)),
                ('parent_path', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opc.opcconnection')),
            ],
            options={
                'unique_together': {('connection', 'opc_name')},
            },
        ),
        migrations.AddField(
            model_name='opcnode',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opc.opcobject'),
        ),
        migrations.CreateModel(
            name='OPCNodeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('source_ts', models.DateTimeField()),
                ('server_ts', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opc.opcnode')),
            ],
            options={
                'indexes': [models.Index(fields=['node', '-source_ts'], name='opc_opcnode_node_id_59b937_idx')],
            },
        ),
    ]
