# Generated by Django 5.2.14 on 2026-05-07 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_etssitereading'),
        ('opc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcconnection',
            name='ets_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opc_connections', to='core.etssite'),
        ),
    ]
