# Generated by Django 5.2.14 on 2026-05-07 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opc', '0002_opcconnection_ets_site'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OPCAlarmRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alarm_type', models.CharField(choices=[('high', 'High Limit'), ('low', 'Low Limit'), ('high_high', 'High High Limit'), ('low_low', 'Low Low Limit'), ('bad_status', 'Bad Status')], max_length=50)),
                ('limit_value', models.FloatField(blank=True, null=True)),
                ('deadband', models.FloatField(default=0)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_rules', to='opc.opcnode')),
            ],
            options={
                'unique_together': {('node', 'name')},
            },
        ),
        migrations.CreateModel(
            name='OPCAlarmLive',
            fields=[
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='live_alarm', serialize=False, to='opc.opcalarmrule')),
                ('is_active', models.BooleanField(default=False)),
                ('value', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('activation_count', models.PositiveIntegerField(default=0)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OPCAlarmEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('start_value', models.FloatField(blank=True, null=True)),
                ('end_value', models.FloatField(blank=True, null=True)),
                ('start_status', models.CharField(blank=True, max_length=50, null=True)),
                ('end_status', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='opc.opcalarmrule')),
            ],
            options={
                'indexes': [models.Index(fields=['rule', '-started_at'], name='opc_opcalar_rule_id_43e004_idx'), models.Index(fields=['ended_at'], name='opc_opcalar_ended_a_d30883_idx')],
            },
        ),
    ]
