# Generated by Django 6.0 on 2026-05-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opc', '0003_opcalarmrule_opcalarmlive_opcalarmevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcconnection',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='opcconnection',
            name='security_policy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='opcconnection',
            name='security_mode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='opcconnection',
            name='auth_type',
            field=models.CharField(default='anonymous', max_length=30),
        ),
        migrations.AddField(
            model_name='opcconnection',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opcconnection',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opcconnection',
            name='client_cert_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opcconnection',
            name='client_key_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opcconnection',
            name='server_cert_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opcconnection',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='opcconnection',
            name='polling_rate_ms',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='opcconnection',
            name='last_polled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opcconnection',
            name='last_error_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='opcconnection',
            name='last_error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
