# Generated by Django 6.0 on 2026-05-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opc', '0004_opcconnection_security_and_polling_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcalarmrule',
            name='alarm_type',
            field=models.CharField(choices=[('high', 'High Limit'), ('low', 'Low Limit'), ('high_high', 'High High Limit'), ('low_low', 'Low Low Limit')], max_length=50),
        ),
    ]
