# Generated by Django 5.2.14 on 2026-05-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opc", "0005_alter_opcalarmrule_alarm_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opcconnection",
            name="endpoint_url",
            field=models.TextField(unique=True),
        ),
    ]
