# Generated by Django 5.2.14 on 2026-05-12 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opc", "0006_alter_opcconnection_endpoint_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opcobject",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="opc.opcconnection",
            ),
        ),
    ]
