# Generated by Django 5.2.14 on 2026-05-12 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_etssite_contract_document_etssitebillingconfig_billing_day"),
        ("opc", "0007_alter_opcobject_connection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opcconnection",
            name="ets_site",
        ),
        migrations.AddField(
            model_name="opcobject",
            name="opc_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="OPCAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("opc_name", models.CharField(max_length=255)),
                ("opc_address", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="opc.opcconnection",
                    ),
                ),
                (
                    "ets_site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opc_assets",
                        to="core.etssite",
                    ),
                ),
            ],
            options={
                "unique_together": {("connection", "opc_name")},
            },
        ),
        migrations.AddField(
            model_name="opcobject",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opc_objects",
                to="opc.opcasset",
            ),
        ),
    ]
