# Generated by Django 5.2.14 on 2026-05-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opc", "0008_remove_opcconnection_ets_site_opcobject_opc_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opcnodehistory",
            name="actual_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opcnodehistory",
            name="actual_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opcnodelive",
            name="actual_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opcnodelive",
            name="actual_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="opcnodehistory",
            name="source_ts",
            field=models.DateTimeField(null=True),
        ),
        migrations.RemoveField(
            model_name="opcnodehistory",
            name="value",
        ),
        migrations.AddField(
            model_name="opcnodehistory",
            name="value",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="opcnodelive",
            name="value",
        ),
        migrations.AddField(
            model_name="opcnodelive",
            name="value",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
