# Generated by Django 6.0 on 2026-05-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opc', '0010_opcalarmevent_is_deleted_opcalarmevent_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcalarmevent',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='opcalarmlive',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='opcasset',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='opcnode',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='opcnodehistory',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='opcobject',
            name='is_deleted',
        ),
    ]
