# Generated by Django 6.0 on 2026-05-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opc', '0012_opcgeneratedsitelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcgeneratedsitelink',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opcgeneratedsitelink',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='opcgeneratedsitelink',
            name='username',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
