# Generated by Django 6.0 on 2026-06-02 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opc', '0013_opcgeneratedsitelink_last_synced_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OPCSiteBaseAlarmRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=255)),
                ('alarm_type', models.CharField(choices=[('high', 'High Limit'), ('low', 'Low Limit'), ('high_high', 'High High Limit'), ('low_low', 'Low Low Limit')], max_length=50)),
                ('limit_value', models.FloatField(blank=True, null=True)),
                ('deadband', models.FloatField(default=0)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_site_base_alarm_rules', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_site_base_alarm_rules', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_site_base_alarm_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('node', 'name')},
            },
        ),
    ]
