# Generated by Django 6.0 on 2026-06-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opc', '0014_opcsitebasealarmrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcsitebasealarmrule',
            name='node',
            field=models.CharField(choices=[('flow_m3h_1', 'Flow (m³/h)'), ('temp_supply_c_2', 'Supply Temp (°C)'), ('temp_return_c_3', 'Return Temp (°C)'), ('energy_mwh_4', 'Energy (MWh)'), ('power_kw_5', 'Power (kW)'), ('volume_m3_6', 'Volume (m³)'), ('temp_diff_k_7', 'Temp Diff (K)'), ('serial_8', 'Serial'), ('address_9', 'Address')], max_length=60),
        ),
    ]
