# Generated by Django 6.0.5 on 2026-05-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OPCGeneratedSiteLink',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('site', models.IntegerField(blank=True, null=True)),
                ('url', models.TextField()),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=64)),
                ('password_hash', models.CharField(blank=True, default='', max_length=128)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('expire_date', models.DateTimeField()),
                ('filter_start_date', models.DateTimeField()),
                ('filter_end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['site', '-created_at'], name='core_opcgen_site_25e262_idx'), models.Index(fields=['expire_date'], name='core_opcgen_expire__40543c_idx')],
            },
        ),
    ]
